// <auto-generated />
using ABPFinal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ABPFinal.Migrations.Listener
{
    [DbContext(typeof(ListenerContext))]
    [Migration("20221208234717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ABPFinal.Listener", b =>
                {
                    b.Property<int>("ListenerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT");

                    b.HasKey("ListenerID");

                    b.ToTable("Listeners");
                });

            modelBuilder.Entity("ABPFinal.Song", b =>
                {
                    b.Property<int>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Length")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListenerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SongName")
                        .HasColumnType("TEXT");

                    b.HasKey("SongID");

                    b.HasIndex("ListenerID");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("ABPFinal.Song", b =>
                {
                    b.HasOne("ABPFinal.Listener", null)
                        .WithMany("SongsList")
                        .HasForeignKey("ListenerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ABPFinal.Listener", b =>
                {
                    b.Navigation("SongsList");
                });
#pragma warning restore 612, 618
        }
    }
}
